routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Client\ClientController@index')->name('home');

Route::get('/category/{id}','Client\ClientController@categoryPage')->name('clientCategory');
Route::get('/service/{slug}','Client\ServiceController@show')->name('clientService');

Auth::routes();

Route::post('/profile/orders/return','Client\ClientController@orderBack')->name('afterOrder');
Route::post('/profile/orders/callback','Client\ClientController@orderBackCallback')->name('updateOrder');

Route::middleware('auth')->group(function () {
    Route::get('/profile/order/create','Client\ClientController@orderCreate')->name('orderCreate');


	Route::get('/profile/orders','Client\ClientController@orders')->name('orders');
	Route::get('/profile/orders/{id}','Client\ClientController@orderDetails')->name('orderDetails');
	Route::post('/profile/orders/{id}','Client\ClientController@reOrder')->name('reorder');

	Route::get('/profile/orders/{id}/service/{service_id}','Client\ClientController@orderItemDetails')->name('orderItemDetails');
	Route::get('/support','Client\TicketController@index')->name('support');
	Route::post('/support','Client\TicketController@store')->name('ticketStore');
	Route::post('/support/{id}','Client\CommentController@store')->name('commentAdd');
	Route::get('/support/add','Client\TicketController@create')->name('ticketAdd');
	Route::get('/support/{id}','Client\TicketController@show')->name('ticketShow');
	Route::post('/service/{slug}','Client\CartController@addItem')->name('addItem');
    Route::delete('/services','Client\CartController@removeItem')->name('removeItem');
    Route::get('/profile','Client\ClientController@profile')->name('profile');
	Route::get('/profile/cart/','Client\CartController@index')->name('cart');
});
Route::middleware('admin')->group(function () {
  Route::prefix('dashboard')->group(function () {
    Route::get('/','AdminDashboardController@index')->name('dashboard');
    Route::resource('services','ServiceController');
    Route::resource('category','CategoryController');
    Route::resource('user','UserController');
    Route::get('/support/','TicketController@index')->name('supportDash');
    Route::get('/support/{id}','TicketController@show')->name('ticketShowDash');
    Route::post('/support/{id}','TicketController@store')->name('CommentAddDash');

	  Route::get('/orders/','OrderController@index')->name('ordersDash');
	  Route::get('/orders/{id}','OrderController@show')->name('OrdersShowDash');
  });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

	//
	protected $fillable = [
		'title',
		'description',
		'parent_id',
		'images',
		'rule'
	];

	public function parent()
	{
		return $this->belongsTo('App\Category', 'parent_id');
	}

	public function children()
	{
		return $this->hasMany('App\Category', 'parent_id');
	}

	public function Services()
	{
		return $this->hasMany('App\Service', 'category_id');
	}

	public static function Tree()
	{
		$categories = self::root()->get();
		$massive = [];
		foreach ($categories as $category) {
			if (count($category->children) == 0):
				$massive[ $category->title ] = [];
			else:
				foreach ($category->children as $children) {
					$massive[ $category->title ][ $children->id ] = $children->title;
				}
			endif;
		}

		return $massive;
	}

	public static function Parents()
	{
		$categories = self::root()->get();
		$massive = [];
		foreach ($categories as $category) {
			$massive[ $category->id ] = $category->title;
		}

		return $massive;
	}

	public static function scopeRoot($query)
	{
		return $query->where('parent_id', null);
	}

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use Redirect;

class CategoryController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::root()->get();
        return view('dashboard.categories.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::Parents();
        $categories[0] = 'Новая категория';
        return view('dashboard.categories.add', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category();

	    $category->title = $request->input('title');
	    $category->description = $request->input('description');

	    if ($request->input('parent_id') == 0) {
		    $category->parent_id = null;
		    $category->rule = $request->input('rule');
		    if($request->file('image')){
			    $image = $request->file('image');

			    $input['imagename'] = time().'.'.$image->getClientOriginalExtension();

			    $destinationPath = public_path('/images');

			    $image->move($destinationPath, $input['imagename']);
			    $category->images = $input['imagename'];
		    }
	    }else{
		    $category->parent_id = $request->input('parent_id');
	    }

	    $category->save();
	    return redirect()->route('category.index')->with('message','Категория добавлена');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $item = Category::findOrFail($id);

        return view('dashboard.categories.show', ['category' => $item]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $category = Category::findOrFail($id);

        $categories = Category::Parents();
        $categories[0] = 'Новая категория';

        return view('dashboard.categories.edit', ['category' => $category, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $category = Category::findOrFail($id);

        $category->title = $request->input('title');
	    $category->description = $request->input('description');

	    if ($request->input('parent_id') == 0) {
		    $category->parent_id = null;
		    $category->rule = $request->input('rule');

		    if($request->file('image')){

			    $image = $request->file('image');

			    $input['imagename'] = time().'.'.$image->getClientOriginalExtension();

			    $destinationPath = public_path('/images');

			    $image->move($destinationPath, $input['imagename']);
			    $category->images = $input['imagename'];

		    }
	    }
	    $category->update();

        return redirect()->route('category.index')->with('message','Категория обновлена');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
	    $category = Category::findOrFail($id);
		$category->delete();

	    return redirect()->route('category.index')->with('message','Категория удалена');
    }
}

resources/views/dashboard/categories/add.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Редактировать</div>

                <div class="panel-body">

                    {{ Form::open( ['method'=>'POST','files' => true , 'route' => ['category.store']]) }}
                    <div class="form-group">
                        {{Form::label('title', 'Название')}}
                        {{Form::text('title',null,['class' => 'form-control'])}}
                    </div>
                    <div class="form-group">
                        {{Form::label('description', 'Описание')}}
                        {{Form::textarea('description', null, ['class' => 'form-control'])}}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                {{Form::label('parent_id', 'Категория')}}
                                {{Form::select('parent_id', $categories, null, ['class' => 'form-control'])}}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {{Form::label('image', 'Изображение')}}
                                {{Form::file('image',['class'=>'form-control'])}}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('rule', 'Валидатор')}}
                        {{Form::text('rule',null,['class'=>'form-control'])}}
                    </div>
                    {{ Form::submit('Сохранить', ['class' => 'btn btn-default btn-xs']) }}
                    {{ Form::close() }}

                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        var editor_config = {
            path_absolute: "/",
            selector: "textarea",
            plugins: [
                "advlist autolink lists link image charmap preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            relative_urls: false,
            file_browser_callback: function (field_name, url, type, win) {
                var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
                var y = window.innerHeight || document.documentElement.clientHeight || document.getElementsByTagName('body')[0].clientHeight;

                var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                if (type == 'image') {
                    cmsURL = cmsURL + "&type=Images";
                } else {
                    cmsURL = cmsURL + "&type=Files";
                }

                tinyMCE.activeEditor.windowManager.open({
                    file: cmsURL,
                    title: 'Filemanager',
                    width: x * 0.8,
                    height: y * 0.8,
                    resizable: "yes",
                    close_previous: "no"
                });
            }
        };

        tinymce.init(editor_config);
    </script>
@endsection

resources/views/dashboard/categories/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Редактировать</div>

                <div class="panel-body">

                    {{ Form::model($category, ['method'=>'PATCH', 'files'=> true, 'route' => ['category.update', $category->id]]) }}
                    <div class="form-group">
                        {{Form::label('title', 'Название')}}
                        {{Form::text('title',null,['class' => 'form-control'])}}
                    </div>
                    <div class="form-group">
                        {{Form::label('description', 'Описание')}}
                        {{Form::textarea('description', null, ['class' => 'form-control'])}}
                    </div>
                    @if ($category->parent_id == null)
						<?php $selected = 0;?>
                    @else
						<?php $selected = $category->parent_id;?>
                    @endif
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                {{Form::label('parent_id', 'Категория')}}
                                {{Form::select('parent_id', $categories, $selected, ['class' => 'form-control'])}}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {{Form::label('image', 'Изображение')}}
                                {{Form::file('image',['class'=>'form-control'])}}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('rule', 'Валидатор')}}
                        {{Form::text('rule',null,['class'=>'form-control'])}}
                    </div>
                    {{ Form::submit('Сохранить', ['class' => 'btn btn-default btn-xs']) }}
                    {{ Form::close() }}

                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        var editor_config = {
            path_absolute: "/",
            selector: "textarea",
            plugins: [
                "advlist autolink lists link image charmap preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            relative_urls: false,
            file_browser_callback: function (field_name, url, type, win) {
                var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
                var y = window.innerHeight || document.documentElement.clientHeight || document.getElementsByTagName('body')[0].clientHeight;

                var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                if (type == 'image') {
                    cmsURL = cmsURL + "&type=Images";
                } else {
                    cmsURL = cmsURL + "&type=Files";
                }

                tinyMCE.activeEditor.windowManager.open({
                    file: cmsURL,
                    title: 'Filemanager',
                    width: x * 0.8,
                    height: y * 0.8,
                    resizable: "yes",
                    close_previous: "no"
                });
            }
        };

        tinymce.init(editor_config);
    </script>
@endsection 

resources/views/dashboard/categories/index.blade.php
@extends('layouts.dashboard') @section('content')
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Категории</div>

      <div class="panel-body">

        @if (session('message'))
          <div class="alert alert-success">
            {{ session('message') }}
          </div>
        @endif
        <ul class="treeMenu">
          @foreach($categories as $category)
          <li><i class="fa fa-folder"></i> <a href="{{route('category.show',['id'=>$category->id])}}">{{$category->title}}</a>
            <ul style="display: none;">
              @foreach($category->children as $child)
              <li><a href="{{route('category.show',['id'=>$child->id])}}"><i class="fa fa-file-o"></i>{{$child->title}}</a></li>
              @endforeach
            </ul>
          </li>
          @endforeach
          <li><a href="{{route('category.create')}}"><i class="fa fa-plus"></i> Добавить новую</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/dashboard/categories/show.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Категория {{$category->id}}</div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-8">
                            <h5>Название</h5>
                            <h3>{{$category->title}}</h3>
                        </div>
                        <div class="col-md-4">
                            @if($category->images)
                                <h5>Иконка</h5>
                                <img src="/images/{{$category->images}}" class="img-responsive" style="width:40px;">
                            @endif
                        </div>
                    </div>
                    <hr>
                    @if($category->parent)
                        <h5>Категория</h5>
                        <h3>{{$category->parent->title}}</h3>
                        <hr>
                    @else
                        <h5>Валидатор</h5>
                        <h3>{{$category->rule}}</h3>
                        <hr>
                    @endif
                    <h5>Описание</h5>
                    <div class="description">
                        {!!$category->description!!}
                    </div>
                </div>
                <div class="panel-footer">
                    <a href="{{route('category.edit',['/id'=>$category->id])}}"
                       class="btn btn-warning">Редактировать</a>
                    {{ Form::open(['method' => 'DELETE', 'route' => ['category.destroy', $category->id]]) }}
                    {{ Form::hidden('id', $category->id) }}
                    {{ Form::submit('Удалить', ['class' => 'btn btn-danger']) }}
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection