routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Client\ClientController@index')->name('home');

Route::get('/category/{id}','Client\ClientController@categoryPage')->name('clientCategory');
Route::get('/service/{slug}','Client\ServiceController@show')->name('clientService');

Auth::routes();

Route::post('/profile/orders/return','Client\ClientController@orderBack')->name('afterOrder');
Route::post('/profile/orders/callback','Client\ClientController@orderBackCallback')->name('updateOrder');

Route::middleware('auth')->group(function () {
    Route::get('/profile/order/create','Client\ClientController@orderCreate')->name('orderCreate');


	Route::get('/profile/orders','Client\ClientController@orders')->name('orders');
	Route::get('/profile/orders/{id}','Client\ClientController@orderDetails')->name('orderDetails');
	Route::post('/profile/orders/{id}','Client\ClientController@reOrder')->name('reorder');

	Route::get('/profile/orders/{id}/service/{service_id}','Client\ClientController@orderItemDetails')->name('orderItemDetails');
	Route::get('/support','Client\TicketController@index')->name('support');
	Route::post('/support','Client\TicketController@store')->name('ticketStore');
	Route::post('/support/{id}','Client\CommentController@store')->name('commentAdd');
	Route::get('/support/add','Client\TicketController@create')->name('ticketAdd');
	Route::get('/support/{id}','Client\TicketController@show')->name('ticketShow');
	Route::post('/service/{slug}','Client\CartController@addItem')->name('addItem');
    Route::delete('/services','Client\CartController@removeItem')->name('removeItem');
    Route::get('/profile','Client\ClientController@profile')->name('profile');
	Route::get('/profile/cart/','Client\CartController@index')->name('cart');
});
Route::middleware('admin')->group(function () {
  Route::prefix('dashboard')->group(function () {
    Route::get('/','AdminDashboardController@index')->name('dashboard');
    Route::resource('services','ServiceController');
    Route::resource('category','CategoryController');
    Route::resource('user','UserController');
    Route::get('/support/','TicketController@index')->name('supportDash');
    Route::get('/support/{id}','TicketController@show')->name('ticketShowDash');
    Route::post('/support/{id}','TicketController@store')->name('CommentAddDash');

	  Route::get('/orders/','OrderController@index')->name('ordersDash');
	  Route::get('/orders/{id}','OrderController@show')->name('OrdersShowDash');
  });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('meta', config('app.name', 'Laravel'))</title>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href="{{route('support')}}">Техподдержка</a></li>
                        <li><a href="{{route('profile')}}">Кабинет</a></li>
                        <li><a href="{{route('orders')}}">История заказов</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Вход</a></li>
                            <li><a href="{{ route('register') }}">Регистрация</a></li>
                        @else
                            <li class="cart">
                                <a href="{{route('cart')}}">Корзина
                                    @if(Auth::user()->cart)
                                        {{Auth::user()->cart->widget()}}
                                    @endif
                                    </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    @if (Auth::user()->isAdmin())
                                    <li><a href="{{route('dashboard')}}">Админ панель</a></li>
                                    @endif
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Выход
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
                @include('header.menu')
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/main.js') }}"></script>
    <script src="{{ asset('js/tinymce/tinymce.min.js') }}"></script>
    @yield('scripts')
</body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>Админ панель</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->

    <link href="{{ asset('css/dashboard/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/dashboard/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	<div class="header">
	     <div class="container">
	        <div class="row">
	           <div class="col-md-5">
	              <!-- Logo -->
	              <div class="logo">
	                 <h1><a href="{{ url('/dashboard') }}">AdminDashboard</a></h1>
	              </div>
	           </div>
	           <div class="col-md-2 col-md-offset-5">
	              <div class="navbar navbar-inverse" role="banner">
	                  <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
	                    <ul class="nav navbar-nav">
	                      <li class="dropdown">
	                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
	                        <ul class="dropdown-menu animated fadeInUp">
	                          <li><a href="{{ route('home')}}">Profile</a></li>
	                          <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">Logout</a>
                              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form></li>
	                        </ul>
	                      </li>
	                    </ul>
	                  </nav>
	              </div>
	           </div>
	        </div>
	     </div>
	</div>

    <div class="page-content">
    	<div class="row">
		  <div class="col-md-2">
		  	<div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li class="current"><a href="{{route('dashboard')}}"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
                    <li class="submenu">
                        <a href="#">
                            <i class="glyphicon glyphicon-list"></i> Пользователи
                            <span class="caret pull-right"></span>
                        </a>
                        <!-- Sub menu -->
                        <ul>
                            <li><a href="{{route('user.index')}}">Все пользователи</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                         <a href="#">
                            <i class="glyphicon glyphicon-list"></i> Сервисы
                            <span class="caret pull-right"></span>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                            <li><a href="{{route('services.index')}}">Все сервисы</a></li>
                            <li><a href="{{route('services.create')}}">Добавить новый сервис</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                         <a href="#">
                            <i class="glyphicon glyphicon-list"></i> Категории
                            <span class="caret pull-right"></span>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                            <li><a href="{{route('category.index')}}">Все категории</a></li>
                            <li><a href="{{route('category.create')}}">Добавить новую категори</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{route('supportDash')}}">Сообщения</a>
                    </li>

                    <li>
                        <a href="{{route('ordersDash')}}">Заказы</a>
                    </li>
                </ul>
             </div>
		  </div>
		  <div class="col-md-10">


        @yield('content')


		  </div>
		</div>
    </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>

    <script src="{{ asset('js/dashboard/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/dashboard/custom.js') }}"></script>

    <script src="{{ asset('js/tinymce/tinymce.min.js') }}"></script>
    @yield('scripts')
  </body>
</html>